// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNu-dNrmHQUQBg3wG0nRKUulnvIXusv0c',
    appId: '1:44683766545:web:b46bebffc2a52ea58ffab0',
    messagingSenderId: '44683766545',
    projectId: 'techfun-22aa2',
    authDomain: 'techfun-22aa2.firebaseapp.com',
    storageBucket: 'techfun-22aa2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLk1si5jStuJ7SOQrJbqAThp4xwJSVpss',
    appId: '1:44683766545:android:06c2b3002a2c65098ffab0',
    messagingSenderId: '44683766545',
    projectId: 'techfun-22aa2',
    storageBucket: 'techfun-22aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSArHtcCy5bJcN0ccK3w1x2Y9qWcfauaA',
    appId: '1:44683766545:ios:e72d021fb0c98cd88ffab0',
    messagingSenderId: '44683766545',
    projectId: 'techfun-22aa2',
    storageBucket: 'techfun-22aa2.firebasestorage.app',
    iosBundleId: 'com.example.techFun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSArHtcCy5bJcN0ccK3w1x2Y9qWcfauaA',
    appId: '1:44683766545:ios:e72d021fb0c98cd88ffab0',
    messagingSenderId: '44683766545',
    projectId: 'techfun-22aa2',
    storageBucket: 'techfun-22aa2.firebasestorage.app',
    iosBundleId: 'com.example.techFun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNu-dNrmHQUQBg3wG0nRKUulnvIXusv0c',
    appId: '1:44683766545:web:b2a88c432de1f6758ffab0',
    messagingSenderId: '44683766545',
    projectId: 'techfun-22aa2',
    authDomain: 'techfun-22aa2.firebaseapp.com',
    storageBucket: 'techfun-22aa2.firebasestorage.app',
  );
}
